In [2]:
# Import modules
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import linear_model
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv("Shill_Bidding_Dataset.csv")

In [4]:
data.head()

Record_ID  Auction_ID Bidder_ID  Bidder_Tendency  Bidding_Ratio  \
0          1         732     _***i         0.200000       0.400000   
1          2         732     g***r         0.024390       0.200000   
2          3         732     t***p         0.142857       0.200000   
3          4         732     7***n         0.100000       0.200000   
4          5         900     z***z         0.051282       0.222222   

   Successive_Outbidding  Last_Bidding  Auction_Bids  Starting_Price_Average  \
0                    0.0      0.000028           0.0                0.993593   
1                    0.0      0.013123           0.0                0.993593   
2                    0.0      0.003042           0.0                0.993593   
3                    0.0      0.097477           0.0                0.993593   
4                    0.0      0.001318           0.0                0.000000   

   Early_Bidding  Winning_Ratio  Auction_Duration  Class  
0       0.000028       0.666667                 5      0  
1       0.013123       0.944444                 5      0  
2       0.003042       1.000000                 5      0  
3       0.097477       1.000000                 5      0  
4       0.001242       0.500000                 7      0

In [5]:
# Drop columns which are irrelevant to our case
data.drop(["Record_ID","Auction_ID","Bidder_ID"],axis=1,\
          inplace=True) 

In [6]:
data.head()

Bidder_Tendency  Bidding_Ratio  Successive_Outbidding  Last_Bidding  \
0         0.200000       0.400000                    0.0      0.000028   
1         0.024390       0.200000                    0.0      0.013123   
2         0.142857       0.200000                    0.0      0.003042   
3         0.100000       0.200000                    0.0      0.097477   
4         0.051282       0.222222                    0.0      0.001318   

   Auction_Bids  Starting_Price_Average  Early_Bidding  Winning_Ratio  \
0           0.0                0.993593       0.000028       0.666667   
1           0.0                0.993593       0.013123       0.944444   
2           0.0                0.993593       0.003042       1.000000   
3           0.0                0.993593       0.097477       1.000000   
4           0.0                0.000000       0.001242       0.500000   

   Auction_Duration  Class  
0                 5      0  
1                 5      0  
2                 5      0  
3                 5      0  
4                 7      0

In [9]:
X = data.drop("Class",axis=1)
y = data["Class"]
# Split the dataset into training and testing sets 
X_train,X_test,y_train,y_test = train_test_split\
                                (X,y,test_size=0.3,\
                                 random_state=1, stratify=y) 

In [10]:
print("Training dataset size: {}, Testing dataset size: {}"\
      .format(X_train.shape,X_test.shape))

Training dataset size: (4424, 9), Testing dataset size: (1897, 9)


In [11]:
# Fit the model using linear regression
linear = linear_model.LinearRegression()
linear.fit(X_train,y_train)

LinearRegression()

In [12]:
linear.predict(X_test)[:10]

array([-0.00375542, -0.00248633, -0.01090699, -0.02753235,  0.01939224,
        0.99493654,  0.02761226, -0.00565047,  0.48101551,  0.00471959])

In [10]:
y_test[:10].values

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [11]:
print("Score on training dataset: {}, "\
      "Score on testing dataset: {}"\
      .format(linear.score(X_train,y_train),\
              linear.score(X_test,y_test))) 

Score on training dataset: 0.8166836356918417, Score on testing dataset: 0.8119909602893054


In [12]:
logit = linear_model.LogisticRegression()
logit.fit(X_train,y_train)

LogisticRegression()

In [13]:
logit.predict(X_test)[:10]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [14]:
y_test[:10].values

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [15]:
print("Score on training dataset: {}, "\
      "Score on testing dataset: {}"\
      .format(logit.score(X_train,y_train),\
              logit.score(X_test,y_test))) 

Score on training dataset: 0.9794303797468354, Score on testing dataset: 0.9715340010542962
