<a href="https://colab.research.google.com/github/vishwesh5/Data-Science-for-Marketing-Analytics/blob/master/Lesson07/Exercise%2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import modules
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import linear_model
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("Shill_Bidding_Dataset.csv")

In [3]:
data.head()

Record_ID  Auction_ID Bidder_ID  ...  Winning_Ratio  Auction_Duration  Class
0          1         732     _***i  ...       0.666667                 5      0
1          2         732     g***r  ...       0.944444                 5      0
2          3         732     t***p  ...       1.000000                 5      0
3          4         732     7***n  ...       1.000000                 5      0
4          5         900     z***z  ...       0.500000                 7      0

[5 rows x 13 columns]

In [4]:
# Drop columns which are irrelevant to our case
data.drop(["Record_ID","Auction_ID","Bidder_ID"],axis=1,inplace=True)

In [5]:
data.head()

Bidder_Tendency  Bidding_Ratio  ...  Auction_Duration  Class
0         0.200000       0.400000  ...                 5      0
1         0.024390       0.200000  ...                 5      0
2         0.142857       0.200000  ...                 5      0
3         0.100000       0.200000  ...                 5      0
4         0.051282       0.222222  ...                 7      0

[5 rows x 10 columns]

In [7]:
X = data.drop("Class",axis=1)
y = data["Class"]
# Split the dataset into training and testing sets
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=1,
                                                 stratify=y)

In [8]:
print("Training dataset size: {}, Testing dataset size: {}".format(X_train.shape,X_test.shape))

Training dataset size: (4424, 9), Testing dataset size: (1897, 9)


In [9]:
# Fit the model using linear regression
linear = linear_model.LinearRegression()
linear.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
linear.predict(X_test)[:10]

array([-0.00375542, -0.00248633, -0.01090699, -0.02753235,  0.01939224,
        0.99493654,  0.02761226, -0.00565047,  0.48101551,  0.00471959])

In [12]:
y_test[:10].values

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [21]:
print("Score on training dataset: {}, Score on testing dataset: {}".format(linear.score(X_train,y_train),linear.score(X_test,y_test)))

Score on training dataset: 0.8166836356918417, Score on testing dataset: 0.8119909602893055


In [15]:
logit = linear_model.LogisticRegression()
logit.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [16]:
logit.predict(X_test)[:10]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [17]:
y_test[:10].values

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [22]:
print("Score on training dataset: {}, Score on testing dataset: {}".format(logit.score(X_train,y_train),logit.score(X_test,y_test)))

Score on training dataset: 0.9794303797468354, Score on testing dataset: 0.9715340010542962
